export const fontFamilies = {
    regular: 'Poppins-Regular',
    medium: 'Poppins-Medium',
    bold: 'Poppins-Bold',
    semiBold: 'Poppins-SemiBold',
    light: 'Poppins-Light',
    extraLight: 'Poppins-ExtraLight',
    thin: 'Poppins-Thin',
    italic: 'Poppins-Italic',
    mediumItalic: 'Poppins-MediumItalic',
    boldItalic: 'Poppins-BoldItalic',
    semiBoldItalic: 'Poppins-SemiBoldItalic',
    lightItalic: 'Poppins-LightItalic',
    extraLightItalic: 'Poppins-ExtraLightItalic',
    thinItalic: 'Poppins-ThinItalic',
    black: 'Poppins-Black',
    blackItalic: 'Poppins-BlackItalic',
    extraBold: 'Poppins-ExtraBold',
    extraBoldItalic: 'Poppins-ExtraBoldItalic',
};